### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by FranzSkuffka** [jackfirth/pyramda#28]
https://github.com/jackfirth/pyramda/blob/a1c47e32948b986b9b98f8e60bcb59859d6045ad/setup.py#L8
```
error: [Errno 2] No such file or directory: 'pip': 'pip'
```

OSX 10.12.6

Python installed through brew.

Pip updated to the latest version.

**Comment by jackfirth** [comment]
This probably has the same cause and solution as #8. Pyramda does bad things when installed to try and cleverly support python 2 and 3 with the same codebase. It should not do those things.

Alas, I don't have the bandwidth to actively maintain Pyramda and likely won't in the near future. If you're interested in contributing I would be quite happy to help point you in the right direction and answer any questions.

**Comment by FranzSkuffka** [comment]
I probably don't have the bandwidth for long-term maintenance either but I would try to take this on.

So why is `call(["pip", "install", "future"])` failing while it works in the shell and how would you go about fixing it?

**Comment by jackfirth** [comment]
I have no idea why it's failing and suspect it's not worth figuring out. I think the right approach is to just drop support for python 2 entirely since the maintenance period for it [comes to an end in just over two years](https://pythonclock.org/). That should let you rip out the fragile `pasteurize` code causing all these problems with minimal impact on the rest of Pyramda.

**Comment by jackfirth** [comment]
@FranzSkuffka This should hopefully be resolved by #36. I'm closing this issue for now, but if installation still fails for you please reopen it.
