### ISSUE TITLE
possibility of writing c bindings for functions

### ISSUE THREAD

**Issue by Rafi993** [jackfirth/pyramda#29]
When doing complex aggregation using pyramda it gets really slow (as expected). May be we could write c bindings for functions so that they could do better.

**Comment by jackfirth** [comment]
The performance of pyramda is likely due to the dynamic checks and varargs overhead of currying. I don't think C bindings would help with that unfortunately.

Broadly speaking, I am not interested in optimizing Pyramda, particularly not without benchmarks. I don't think the work involved would be worth it. If you have a specific use case where performance is an issue, we can talk about that and I'm sure we'll figure something out.
